### ISSUE TITLE
Fix error while installing modloader

### ISSUE THREAD

**Issue by tygoee** [tygoee/mcm-manager#1]
When installing the modloader, it gives an error when trying to install it:

```log
Manifest file location (default: example-manifest.json): 
Install location (default: share/.minecraft): 
Install side (client/server, default: client): 
Do you want to install the modloader? (Y/n, default: n): y
Launcher location (default: ~/.minecraft): 

Modpack version: 1.20.1
Mod loader: forge
Mod loader version: 47.1.0

Mods:
  (...)

Resourcepacks:
  (...)

Shaderpacks:
  (...)

127 mods, 9 recourcepacks, 1 shaderpacks
Total file size: 1 GB
Continue? (Y/n) y
Traceback (most recent call last):                                                                                                              
  File "/home/tygoe/Documents/code/github/mcm-manager/src/main.py", line 188, in <module>
    install(mcm_location, launcher_path=launcher_location, side=side)
  File "/home/tygoe/Documents/code/github/mcm-manager/src/main.py", line 129, in install
    _install_modloader()
  File "/home/tygoe/Documents/code/github/mcm-manager/src/main.py", line 120, in _install_modloader
    modloaders.forge(modpack_version, modloader_version,
  File "/home/tygoe/Documents/code/github/mcm-manager/src/install/modloaders.py", line 142, in __init__
    self.build_processors()
  File "/home/tygoe/Documents/code/github/mcm-manager/src/install/modloaders.py", line 335, in build_processors
    args: list[str] = [
                      ^
  File "/home/tygoe/Documents/code/github/mcm-manager/src/install/modloaders.py", line 336, in <listcomp>
    self.replace_arg_vars(arg, data) for arg in processor['args']
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tygoe/Documents/code/github/mcm-manager/src/install/modloaders.py", line 151, in replace_arg_vars
    archive.extract(arg[1:], self.temp_dir)
  File "/usr/lib/python3.11/zipfile.py", line 1660, in extract
    return self._extract_member(member, path, pwd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/zipfile.py", line 1699, in _extract_member
    member = self.getinfo(member)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/zipfile.py", line 1473, in getinfo
    raise KeyError(
KeyError: "There is no item named 'home/tygoe/.minecraft/versions/1.20.1/1.20.1.jar' in the archive"
```

**Comment by tygoee** [comment]
This is fixed after commit 831d023cc08627b0f7997e00d1c032b35ea5a622
